### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by tejas-techstack**
Updated the README with command to include a command to be able to run rps.py on ubuntu

### CODE REVIEW

**Comment by bun137** [comment]
@tejas-techstack amazing!, you could go ahead and work on the issue! 10 points on the way!
Please update your progress in 30 mins!

**Comment by bun137** [comment]
!bounty 10

**Comment by tejas-techstack** [comment]
added the tie sound effect for the game, more ui changes on the way

**Comment by bun137** [comment]
@tejas-techstack the tie sound effect is a "six" ? :joy: :joy:

**Comment by tejas-techstack** [comment]
oh its a 6? well i think i misheard it in the whole mess of sounds i will change it to something else in the next push

**Comment by bun137** [comment]
@tejas-techstack cool cool nps!

**Comment by tejas-techstack** [comment]
updated the background making few final changes

**Comment by bun137** [comment]
lgtm!

**Comment by tejas-techstack** [comment]
hey im done anything else necessary?

**Comment by tejas-techstack** [comment]
if not im done , cool project to work on

**Comment by tejas-techstack** [comment]
hey im done please check

**Comment by bun137** [comment]
@tejas-techstack crazyy UI update!!!!

**Comment by bun137** [comment]
!bounty 60

**Comment by bun137** [comment]
!bounty 70

**Pull request closed without merging**
